// Generated by CoffeeScript 1.10.0
(function() {
  var Gobgp, grpc, libgobgp, protoDescriptor;

  grpc = require('grpc');

  protoDescriptor = grpc.load(__dirname + "/deps/gobgp/gobgp.proto").gobgpapi;

  libgobgp = require('./build/Release/gobgp');

  Gobgp = (function() {
    function Gobgp(server) {
      this.stub = new protoDescriptor.GobgpApi(server, grpc.Credentials.createInsecure());
    }

    Gobgp.prototype.getRib = function(options, callback) {
      if (typeof options.family === 'string') {
        options.family = this.routeFamily(options.family);
      }
      return this.stub.getRib(options, (function(_this) {
        return function(err, table) {
          if (err) {
            return callback(err);
          }
          table.destinations.forEach(function(destination) {
            return destination.paths = destination.paths.map(function(path) {
              var decoded;
              decoded = JSON.parse(_this.decodePath(path));
              path.nlri = decoded.nlri.value;
              path.attrs = decoded.attrs;
              delete path.pattrs;
              return path;
            });
          });
          if (callback) {
            return callback(null, table);
          }
        };
      })(this));
    };

    Gobgp.prototype.modPath = function(options, path, callback) {
      if (typeof path === 'string') {
        path = this.serializePath(options.family, path);
        path.is_withdraw = options.withdraw;
      }
      if (!path) {
        return callback("Invalid argument: path");
      }
      return this.stub.modPath({
        path: path
      }, function(err, response) {
        if (err) {
          return callback(err);
        }
        if (callback) {
          return callback(null, response);
        }
      });
    };

    Gobgp.prototype.routeFamily = function(string) {
      return libgobgp.get_route_family(string);
    };

    Gobgp.prototype.serializePath = function(family, string) {
      if (typeof family === 'string') {
        family = this.routeFamily(family);
      }
      return libgobgp.serialize_path(family, string);
    };

    Gobgp.prototype.decodePath = function(path) {
      return libgobgp.decode_path(path);
    };

    return Gobgp;

  })();

  module.exports = Gobgp;

}).call(this);
